[project]
name = "diquark"
version = "0.1.0"
description = ""
authors = [
    { name = "Ioan-Mihail Dinu", email = "ioan-mihail.dinu@cern.ch" },
    { name = "Gabriel Majeri", email = "gabriel.majeri@cern.ch" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0,<4",
    "tqdm>=4.67",
    "pyyaml>=6,<7",
    "uproot>=5.6",
    "awkward>=2.8.5,<3",
    "numpy>=2.5.0",
    "scipy>=1.16",
    "scikit-learn>=1.9,<2",
    "xgboost>=3.3.0",
    "matplotlib>=3.10,<4",
    "plotly>=6.2,<7",
    "kaleido>=1,<2",
    "joblib>=1.5.3",
    "pyarrow>=24.0.0",
]

[project.scripts]
diquark = "diquark.analysis:main"

[build-system]
requires = ["uv_build >= 0.11.23, <0.12.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "diquark"
module-root = ""

[dependency-groups]
dev = ["ruff>=0.15.20"]
