version: 1.0
backgrounds:
  mass_cut: 7500
  base_directory: "/data/gmajeri/diquark-simulations/pythia_with_ptj_100/delphes_output"
  file_name_mapping:
    gg_bbbar: "01_gg_bbbar"
    gg_ccbar: "02_gg_ccbar"
    gg_gg: "03_gg_gg"
    qqbar_gg: "04_qqbar_gg"
    gg_qqbar: "05_gg_qqbar"
    qg_qg: "06_qg_qg"
    qqbar_bbbar: "07_qqbar_bbbar"
    qqbar_ccbar: "08_qqbar_ccbar"
    qq_qq: "09_qq_qq"
    qqbar_qqbarNew: "10_qqbar_qqbarNew"
    qq_hbb_hadronic: "11_qq_hbb_hadronic"
    gg_hbb_hadronic: "12_gg_hbb_hadronic"
    gg_Hg: "13_gg_Hg"
    qg_Hq_loop: "14_qg_Hq"
    ff_HZ: "18_ff_HZ"
    ff_HW: "19_ff_HW"
    ff_Hff: "20_ff_Hff"
    ff_Hff2: "21_ff_Hff2"
    gg_Httbar: "22_gg_Httbar"
    qq_Httbar: "23_qq_Httbar"
    qg_Hq: "24_qg_Hq"
    ffbar_Wgm: "25_ffbar_Wgm"
    qg_Wj_hadronic: "26_qg_Wj_hadronic"
    qqbar_Wj_hadronic: "27_qqbar_Wj_hadronic"
    ff_ZW_bkg: "28_ff_ZW_bkg"
    ff_WW_bkg: "29_ff_WW_bkg"
    ff_gmZgmZ_bkg: "30_ff_gmZgmZ_bkg"
    gg_ttbar_bkg_hadronic: "31_gg_ttbar_bkg_hadronic"
    qq_ttbar_bkg_hadronic: "32_qq_ttbar_bkg_hadronic"
  cross_sections:
    gg_bbbar: 1.130E-04
    gg_ccbar: 1.131E-04
    gg_gg: 2.697
    qqbar_gg: 5.959E-03
    gg_qqbar: 3.388E-04
    qg_qg: 1.232E+02
    qqbar_bbbar: 7.833E-05
    qqbar_ccbar: 7.829E-05
    qq_qq: 1.088E+03
    qqbar_qqbarNew: 2.354E-04
    qq_hbb_hadronic: 2.699E-10
    gg_hbb_hadronic: 5.961E-10
    gg_Hg: 1.831E-05
    qg_Hq_loop: 4.372E-04
    ff_HZ: 5.656E-08
    ff_HW: 6.467E-08
    ff_Hff: 6.345E-03
    ff_Hff2: 8.253E-03
    gg_Httbar: 4.128E-07
    qq_Httbar: 5.391E-07
    qg_Hq: 1.831E-10
    ffbar_Wgm: 4.248E-06
    qg_Wj_hadronic: 7.234E-04
    qqbar_Wj_hadronic: 3.092E-04
    ff_ZW_bkg: 8.997E-06
    ff_WW_bkg: 2.226E-05
    ff_gmZgmZ_bkg: 1.351E-06
    gg_ttbar_bkg_hadronic: 3.009E-05
    qq_ttbar_bkg_hadronic: 3.660E-05
