version: 1.0
backgrounds:
  mass_cut: 6500
  base_directory: "/data/iduminic/diquark-analysis/full-hadro/bkg/6jets/136/100k/136_6500/"
  file_name_mapping:
    gg_bbbar: "01_gg_bbbar"
    gg_ccbar: "02_gg_ccbar"
    gg_gg: "03_gg_gg"
    qqbar_gg: "04_qqbar_gg"
    gg_qqbar: "05_gg_qqbar"
    qg_qg: "06_qg_qg"
    qqbar_bbbar: "07_qqbar_bbbar"
    qqbar_ccbar: "08_qqbar_ccbar"
    qq_qq: "09_qq_qq"
    qqbar_qqbarNew: "10_qqbar_qqbarNew"
    qq_hbb_hadronic: "11_qq_hbb_hadronic"
    gg_hbb_hadronic: "12_gg_hbb_hadronic"
    gg_Hg: "13_gg_Hg"
    qg_Hq_loop: "14_qg_Hq"
    ff_HZ: "18_ff_HZ"
    ff_HW: "19_ff_HW"
    ff_Hff: "20_ff_Hff"
    ff_Hff2: "21_ff_Hff2"
    gg_Httbar: "22_gg_Httbar"
    qq_Httbar: "23_qq_Httbar"
    qg_Hq: "24_qg_Hq"
    ffbar_Wgm: "25_ffbar_Wgm"
    qg_Wj_hadronic: "26_qg_Wj_hadronic"
    qqbar_Wj_hadronic: "27_qqbar_Wj_hadronic"
    ff_ZW_bkg: "28_ff_ZW_bkg"
    ff_WW_bkg: "29_ff_WW_bkg"
    ff_gmZgmZ_bkg: "30_ff_gmZgmZ_bkg"
    gg_ttbar_bkg_hadronic: "31_gg_ttbar_bkg_hadronic"
    qq_ttbar_bkg_hadronic: "32_qq_ttbar_bkg_hadronic"
  cross_sections:
    gg_bbbar: 3.491E-02
    gg_ccbar: 3.206E-01
    gg_gg: 3.249E+08
    qqbar_gg: 8.525E+00
    gg_qqbar: 2.742E+00
    qg_qg: 4.618E+09
    qqbar_bbbar: 9.975E-04
    qqbar_ccbar: 1.002E-03
    qq_qq: 1.085E+10
    qqbar_qqbarNew: 3.005E-03
    qq_hbb_hadronic: 3.509E-09
    gg_hbb_hadronic: 3.399E-07
    gg_Hg: 1.359E-02
    qg_Hq_loop: 1.157E-01
    ff_HZ: 7.241E-07
    ff_HW: 1.041E-06
    ff_Hff: 2.881E-01
    ff_Hff2: 6.119E-01
    gg_Httbar: 7.088E-06
    qq_Httbar: 6.695E-06
    qg_Hq: 8.029E-09
    ffbar_Wgm: 8.854E-04
    qg_Wj_hadronic: 2.279E-01
    qqbar_Wj_hadronic: 9.876E-02
    ff_ZW_bkg: 4.024E-04
    ff_WW_bkg: 9.666E-04
    ff_gmZgmZ_bkg: 9.065E-05
    gg_ttbar_bkg_hadronic: 5.051E-04
    qq_ttbar_bkg_hadronic: 4.646E-04
