version: 1.0
backgrounds:
  mass_cut: 7500
  base_directory: "/data/gmajeri/diquark-simulations/pythia_with_ptj_2500/delphes_output"
  file_name_mapping:
    gg_bbbar: "01_gg_bbbar"
    gg_ccbar: "02_gg_ccbar"
    gg_gg: "03_gg_gg"
    qqbar_gg: "04_qqbar_gg"
    gg_qqbar: "05_gg_qqbar"
    qg_qg: "06_qg_qg"
    qqbar_bbbar: "07_qqbar_bbbar"
    qqbar_ccbar: "08_qqbar_ccbar"
    qq_qq: "09_qq_qq"
    qqbar_qqbarNew: "10_qqbar_qqbarNew"
    qq_hbb_hadronic: "11_qq_hbb_hadronic"
    gg_hbb_hadronic: "12_gg_hbb_hadronic"
    gg_Hg: "13_gg_Hg"
    qg_Hq_loop: "14_qg_Hq"
    ff_HZ: "18_ff_HZ"
    ff_HW: "19_ff_HW"
    ff_Hff: "20_ff_Hff"
    ff_Hff2: "21_ff_Hff2"
    gg_Httbar: "22_gg_Httbar"
    qq_Httbar: "23_qq_Httbar"
    qg_Hq: "24_qg_Hq"
    ffbar_Wgm: "25_ffbar_Wgm"
    qg_Wj_hadronic: "26_qg_Wj_hadronic"
    qqbar_Wj_hadronic: "27_qqbar_Wj_hadronic"
    ff_ZW_bkg: "28_ff_ZW_bkg"
    ff_WW_bkg: "29_ff_WW_bkg"
    ff_gmZgmZ_bkg: "30_ff_gmZgmZ_bkg"
    gg_ttbar_bkg_hadronic: "31_gg_ttbar_bkg_hadronic"
    qq_ttbar_bkg_hadronic: "32_qq_ttbar_bkg_hadronic"
  cross_sections:
    gg_bbbar: 3.517E-06
    gg_ccbar: 3.529E-06
    gg_gg: 4.233E-04
    qqbar_gg: 2.083E-04
    gg_qqbar: 1.056E-05
    qg_qg: 2.074E-02
    qqbar_bbbar: 4.616E-05
    qqbar_ccbar: 4.606E-05
    qq_qq: 1.766E-01
    qqbar_qqbarNew: 1.387E-04
    qq_hbb_hadronic: 5.316E-14
    gg_hbb_hadronic: 2.841E-15
    gg_Hg: 1.260E-06
    qg_Hq_loop: 3.442E-05
    ff_HZ: 5.084E-08
    ff_HW: 5.813E-08
    ff_Hff: 2.430E-12
    ff_Hff2: 2.258E-12
    gg_Httbar: 4.182E-12
    qq_Httbar: 8.100E-11
    qg_Hq: 1.263E-11
    ffbar_Wgm: 1.504E-07
    qg_Wj_hadronic: 8.829E-05
    qqbar_Wj_hadronic: 2.192E-05
    ff_ZW_bkg: 3.477E-07
    ff_WW_bkg: 3.514E-06
    ff_gmZgmZ_bkg: 1.148E-07
    gg_ttbar_bkg_hadronic: 1.636E-06
    qq_ttbar_bkg_hadronic: 2.155E-05
