version: 1.0
backgrounds:
  mass_cut: 7500
  base_directory: "/data/gmajeri/diquark-simulations/pythia_with_ptj_10/delphes_output"
  file_name_mapping:
    gg_bbbar: "01_gg_bbbar"
    gg_ccbar: "02_gg_ccbar"
    gg_gg: "03_gg_gg"
    qqbar_gg: "04_qqbar_gg"
    gg_qqbar: "05_gg_qqbar"
    qg_qg: "06_qg_qg"
    qqbar_bbbar: "07_qqbar_bbbar"
    qqbar_ccbar: "08_qqbar_ccbar"
    qq_qq: "09_qq_qq"
    qqbar_qqbarNew: "10_qqbar_qqbarNew"
    qq_hbb_hadronic: "11_qq_hbb_hadronic"
    gg_hbb_hadronic: "12_gg_hbb_hadronic"
    gg_Hg: "13_gg_Hg"
    qg_Hq_loop: "14_qg_Hq"
    ff_HZ: "18_ff_HZ"
    ff_HW: "19_ff_HW"
    ff_Hff: "20_ff_Hff"
    ff_Hff2: "21_ff_Hff2"
    gg_Httbar: "22_gg_Httbar"
    qq_Httbar: "23_qq_Httbar"
    qg_Hq: "24_qg_Hq"
    ffbar_Wgm: "25_ffbar_Wgm"
    qg_Wj_hadronic: "26_qg_Wj_hadronic"
    qqbar_Wj_hadronic: "27_qqbar_Wj_hadronic"
    ff_ZW_bkg: "28_ff_ZW_bkg"
    ff_WW_bkg: "29_ff_WW_bkg"
    ff_gmZgmZ_bkg: "30_ff_gmZgmZ_bkg"
    gg_ttbar_bkg_hadronic: "31_gg_ttbar_bkg_hadronic"
    qq_ttbar_bkg_hadronic: "32_qq_ttbar_bkg_hadronic"
  cross_sections:
    gg_bbbar: 8.618E-04
    gg_ccbar: 9.577E-04
    gg_gg: 2.846E+03
    qqbar_gg: 4.032E-02
    gg_qqbar: 2.914E-03
    qg_qg: 1.121E+05
    qqbar_bbbar: 7.886E-05
    qqbar_ccbar: 7.872E-05
    qq_qq: 8.041E+05
    qqbar_qqbarNew: 2.367E-04
    qq_hbb_hadronic: 2.937E-10
    gg_hbb_hadronic: 8.587E-09
    gg_Hg: 8.894E-05
    qg_Hq_loop: 1.893E-03
    ff_HZ: 5.658E-08
    ff_HW: 6.485E-08
    ff_Hff: 5.497E-02
    ff_Hff2: 1.016E-01
    gg_Httbar: 5.169E-07
    qq_Httbar: 5.548E-02
    qg_Hq: 4.329E-10
    ffbar_Wgm: 1.475E-05
    qg_Wj_hadronic: 2.963E-03
    qqbar_Wj_hadronic: 1.279E-03
    ff_ZW_bkg: 2.039E-05
    ff_WW_bkg: 3.361E-05
    ff_gmZgmZ_bkg: 2.745E-06
    gg_ttbar_bkg_hadronic: 3.372E-05
    qq_ttbar_bkg_hadronic: 3.669E-05
