version: 1.0
backgrounds:
  mass_cut: 8250
  base_directory: "/data/iduminic/diquark-analysis/full-hadro/bkg/6jets/136/100k/136_8250/"
  file_name_mapping:
    gg_bbbar: "01_gg_bbbar"
    gg_ccbar: "02_gg_ccbar"
    gg_gg: "03_gg_gg"
    qqbar_gg: "04_qqbar_gg"
    gg_qqbar: "05_gg_qqbar"
    qg_qg: "06_qg_qg"
    qqbar_bbbar: "07_qqbar_bbbar"
    qqbar_ccbar: "08_qqbar_ccbar"
    qq_qq: "09_qq_qq"
    qqbar_qqbarNew: "10_qqbar_qqbarNew"
    qq_hbb_hadronic: "11_qq_hbb_hadronic"
    gg_hbb_hadronic: "12_gg_hbb_hadronic"
    gg_Hg: "13_gg_Hg"
    qg_Hq_loop: "14_qg_Hq"
    ff_HZ: "18_ff_HZ"
    ff_HW: "19_ff_HW"
    ff_Hff: "20_ff_Hff"
    ff_Hff2: "21_ff_Hff2"
    gg_Httbar: "22_gg_Httbar"
    qq_Httbar: "23_qq_Httbar"
    qg_Hq: "24_qg_Hq"
    ffbar_Wgm: "25_ffbar_Wgm"
    qg_Wj_hadronic: "26_qg_Wj_hadronic"
    qqbar_Wj_hadronic: "27_qqbar_Wj_hadronic"
    ff_ZW_bkg: "28_ff_ZW_bkg"
    ff_WW_bkg: "29_ff_WW_bkg"
    ff_gmZgmZ_bkg: "30_ff_gmZgmZ_bkg"
    gg_ttbar_bkg_hadronic: "31_gg_ttbar_bkg_hadronic"
    qq_ttbar_bkg_hadronic: "32_qq_ttbar_bkg_hadronic"
  cross_sections:
    gg_bbbar: 3.048E-04
    gg_ccbar: 3.087E-03
    gg_gg: 5.158E+06
    qqbar_gg: 2.010E-01
    gg_qqbar: 2.769E-02
    qg_qg: 1.823E+08
    qqbar_bbbar: 9.899E-06
    qqbar_ccbar: 9.887E-06
    qq_qq: 9.809E+08
    qqbar_qqbarNew: 2.974E-05
    qq_hbb_hadronic: 3.828E-11
    gg_hbb_hadronic: 3.063E-09
    gg_Hg: 2.055E-04
    qg_Hq_loop: 4.081E-03
    ff_HZ: 7.076E-09
    ff_HW: 7.177E-09
    ff_Hff: 1.432E-02
    ff_Hff2: 2.353E-02
    gg_Httbar: 6.222E-08
    qq_Httbar: 7.170E-08
    qg_Hq: 7.096E-11
    ffbar_Wgm: 1.040E-05
    qg_Wj_hadronic: 5.273E-03
    qqbar_Wj_hadronic: 1.189E-03
    ff_ZW_bkg: 3.483E-06
    ff_WW_bkg: 1.424E-05
    ff_gmZgmZ_bkg: 1.176E-06
    gg_ttbar_bkg_hadronic: 3.812E-06
    qq_ttbar_bkg_hadronic: 4.603E-06
