version: 1.0
backgrounds:
  mass_cut: 7250
  base_directory: "/data/iduminic/diquark-analysis/full-hadro/bkg/6jets/136/100k/136_7250/"
  file_name_mapping:
    gg_bbbar: "01_gg_bbbar"
    gg_ccbar: "02_gg_ccbar"
    gg_gg: "03_gg_gg"
    qqbar_gg: "04_qqbar_gg"
    gg_qqbar: "05_gg_qqbar"
    qg_qg: "06_qg_qg"
    qqbar_bbbar: "07_qqbar_bbbar"
    qqbar_ccbar: "08_qqbar_ccbar"
    qq_qq: "09_qq_qq"
    qqbar_qqbarNew: "10_qqbar_qqbarNew"
    qq_hbb_hadronic: "11_qq_hbb_hadronic"
    gg_hbb_hadronic: "12_gg_hbb_hadronic"
    gg_Hg: "13_gg_Hg"
    qg_Hq_loop: "14_qg_Hq"
    ff_HZ: "18_ff_HZ"
    ff_HW: "19_ff_HW"
    ff_Hff: "20_ff_Hff"
    ff_Hff2: "21_ff_Hff2"
    gg_Httbar: "22_gg_Httbar"
    qq_Httbar: "23_qq_Httbar"
    qg_Hq: "24_qg_Hq"
    ffbar_Wgm: "25_ffbar_Wgm"
    qg_Wj_hadronic: "26_qg_Wj_hadronic"
    qqbar_Wj_hadronic: "27_qqbar_Wj_hadronic"
    ff_ZW_bkg: "28_ff_ZW_bkg"
    ff_WW_bkg: "29_ff_WW_bkg"
    ff_gmZgmZ_bkg: "30_ff_gmZgmZ_bkg"
    gg_ttbar_bkg_hadronic: "31_gg_ttbar_bkg_hadronic"
    qq_ttbar_bkg_hadronic: "32_qq_ttbar_bkg_hadronic"
  cross_sections:
    gg_bbbar: 4.989E-03
    gg_ccbar: 4.866E-02
    gg_gg: 6.296E+07
    qqbar_gg: 1.890E+00
    gg_qqbar: 4.296E-01
    qg_qg: 1.280E+09
    qqbar_bbbar: 1.524E-04
    qqbar_ccbar: 1.521E-04
    qq_qq: 4.196E+09
    qqbar_qqbarNew: 4.554E-04
    qq_hbb_hadronic: 5.594E-10
    gg_hbb_hadronic: 4.931E-08
    gg_Hg: 2.544E-03
    qg_Hq_loop: 3.048E-02
    ff_HZ: 1.094E-07
    ff_HW: 1.321E-07
    ff_Hff: 8.740E-02
    ff_Hff2: 1.691E-01
    gg_Httbar: 1.017E-06
    qq_Httbar: 1.057E-06
    qg_Hq: 1.083E-09
    ffbar_Wgm: 1.503E-04
    qg_Wj_hadronic: 4.946E-02
    qqbar_Wj_hadronic: 1.700E-02
    ff_ZW_bkg: 5.824E-05
    ff_WW_bkg: 1.761E-04
    ff_gmZgmZ_bkg: 1.544E-05
    gg_ttbar_bkg_hadronic: 6.757E-05
    qq_ttbar_bkg_hadronic: 7.087E-05
