version: 1.0
signal:
  file: "/data/gmajeri/diquark-simulations/runs/diquark-many-jets/Suu_8TeV/data/signal/Suu_chichi_wbht_jjb_bbt/Events/run_01/tag_1_delphes_events.root"
  cross_section: 2.934E-03
  chi_mass: 2000
  suu_mass: 8000
