signal:
  file: "/mnt/home/gabrielmajeri/Projects/Research/HEP/madgraph-script-generator/simulations/diquark-many-jets/Suu_8TeV/data/signal/Suu_chichi_wbht_jjb_bbt_8TeV/Events/run_01/tag_1_delphes_events.root"
  cross_section: 2.936E-03
  chi_mass: 2000
  suu_mass: 8000
