version: 1.0
backgrounds:
  file_names:
    qcd_2_to_2_run_1: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets/Suu_8TeV/data/background/qcd_2_to_2/Events/run_01/tag_1_delphes_events.root"
    qcd_2_to_2_run_2: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-2/Suu_8TeV/data/background/qcd_2_to_2/Events/run_01/tag_1_delphes_events.root"
    qcd_2_to_2_run_3: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-3/Suu_8TeV/data/background/qcd_2_to_2/Events/run_01/tag_1_delphes_events.root"

    qcd_2_to_3_run_1: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets/Suu_8TeV/data/background/qcd_2_to_3/Events/run_01/tag_1_delphes_events.root"
    qcd_2_to_3_run_2: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-2/Suu_8TeV/data/background/qcd_2_to_3/Events/run_01/tag_1_delphes_events.root"
    qcd_2_to_3_run_3: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-3/Suu_8TeV/data/background/qcd_2_to_3/Events/run_01/tag_1_delphes_events.root"

    qcd_2_to_4_run_1: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets/Suu_8TeV/data/background/qcd_2_to_4/Events/run_01/tag_1_delphes_events.root"
    qcd_2_to_4_run_2: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-2/Suu_8TeV/data/background/qcd_2_to_4/Events/run_01/tag_1_delphes_events.root"
    qcd_2_to_4_run_3: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-3/Suu_8TeV/data/background/qcd_2_to_4/Events/run_01/tag_1_delphes_events.root"

    single_boson_run_1: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets/Suu_8TeV/data/background/single_boson/Events/run_01/tag_1_delphes_events.root"

    diboson_run_1: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets/Suu_8TeV/data/background/diboson/Events/run_01/tag_1_delphes_events.root"

    ttbar_run_1: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets/Suu_8TeV/data/background/ttbar/Events/run_01/tag_1_delphes_events.root"
    ttbar_run_2: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-2/Suu_8TeV/data/background/ttbar/Events/run_01/tag_1_delphes_events.root"
    ttbar_run_3: "/mnt/projects/acc-c-fiz-26-001/ultraheavy-diquark/simulations/diquark-many-jets-run-3/Suu_8TeV/data/background/ttbar/Events/run_01/tag_1_delphes_events.root"

  cross_sections:
    qcd_2_to_2_run_1: 3.161E+00
    qcd_2_to_2_run_2: 3.159E+00
    qcd_2_to_2_run_3: 3.164E+00

    qcd_2_to_3_run_1: 9.864E-01
    qcd_2_to_3_run_2: 9.894E-01
    qcd_2_to_3_run_3: 9.880E-01

    qcd_2_to_4_run_1: 1.160E-01
    qcd_2_to_4_run_2: 1.161E-01
    qcd_2_to_4_run_3: 1.163E-01

    single_boson_run_1: 2.691E-04

    diboson_run_1: 2.714E-04

    ttbar_run_1: 7.967E-03
    ttbar_run_2: 7.984E-03
    ttbar_run_3: 8.183E-03
