version: 1.0
backgrounds:
  file_names:
    qcd: "/data/gmajeri/madgraph-script-generator/simulations/diquark-repro-my-cuts/Suu_8TeV/data/background/qcd/Events/run_01/tag_1_delphes_events.root"
    # qcd_2_to_2: "/data/gmajeri/madgraph-script-generator/simulations/qcd-backgrounds-ptj/Suu_8TeV/data/qcd_2_to_2/Events/run_01/tag_1_delphes_events.root"
    # qcd_2_to_3: "/data/gmajeri/madgraph-script-generator/simulations/qcd-backgrounds-ptj/Suu_8TeV/data/qcd_2_to_3/Events/run_01/tag_1_delphes_events.root"
    # qcd_2_to_4: "/data/gmajeri/madgraph-script-generator/simulations/qcd-backgrounds-ptj/Suu_8TeV/data/qcd_2_to_4/Events/run_01/tag_1_delphes_events.root"
    qcd_run2: "/data/gmajeri/madgraph-script-generator/simulations/diquark-repro-my-cuts/Suu_8TeV/data/background/qcd_run2/Events/run_01/tag_1_delphes_events.root"
    qcd_run3: "/data/gmajeri/madgraph-script-generator/simulations/diquark-repro-my-cuts/Suu_8TeV/data/background/qcd_run3/Events/run_01/tag_1_delphes_events.root"
    ttbar: "/data/gmajeri/madgraph-script-generator/simulations/diquark-repro-my-cuts/Suu_8TeV/data/background/ttbar/Events/run_01/tag_1_delphes_events.root"
    diboson: "/data/gmajeri/madgraph-script-generator/simulations/diquark-repro-my-cuts/Suu_8TeV/data/background/diboson/Events/run_01/tag_1_delphes_events.root"
    w_plus_jets: "/data/gmajeri/madgraph-script-generator/simulations/diquark-repro-my-cuts/Suu_8TeV/data/background/w_plus_jets/Events/run_01/tag_1_delphes_events.root"
  cross_sections:
    qcd: 0.4808
    # qcd_2_to_2: 0.472
    # qcd_2_to_3: 1.022E-02
    # qcd_2_to_4: 2.698E-05
    qcd_run2: 0.4792
    qcd_run3: 0.4802
    ttbar: 2.518E-03
    diboson: 6.494E-03
    w_plus_jets: 3.338E-02
